### ISSUE TITLE
How to pass/receive Rust types to/from wasm

### ISSUE THREAD

**Issue by gterzian** [adrien-zinger/wasm-simulation#2]
Did you figure out how to pass Rust types to the wasm module as an API, and how to "receive" those as arguments to the host functions?

That is were I was blocked with https://github.com/massalabs/massa/pull/1837/files#diff-096adcd46ddbfad979faeadef5780f103f5355b89722c6a0557b765e55558dfeR16

@adrien-zinger @yvan-sraka

**Comment by adrien-zinger** [comment]
That is THE question. @gterzian. For the moment you can see (in the wasmer-as module) that we have to read and parse the memory content of the VM to communicate between rust and wat. We're blocked at the same point and we'll need to start a big discussion!

We're preparing with @yvan-sraka ad @AureliaDolo  a document that list every known issues and developments. For now you can read how assemblyscript write structure in the linear memory [here](https://www.assemblyscript.org/memory.html#importing-memory) that is their approach.

wasm-bindgen does something else, so I would like to find how the data are structured in the wat when we translate rust to wasm! With a documentation or experimentation.

**Comment by gterzian** [comment]
@yvan-sraka In the light of your commit above, could you please provide more explanation on "how it works"? It was not immediately clear to me when reading the code. 

cc @adrien-zinger @AureliaDolo @damip

**Comment by gterzian** [comment]
On another note, have you looked at this as a potential solution already: https://github.com/wasmerio/wasi-data-rust ?

@yvan-sraka  @adrien-zinger @AureliaDolo @damip

**Comment by yvan-sraka** [comment]
The link you provide use **WASM Interface Types** and looks great!

My intention was to provide a quite language-agnostic solution by passing JSON through an `ENV` variable (using `WasiEnv`), which is a bit of a hack, but an easy to re-use one :)

**Comment by yvan-sraka** [comment]
Here https://github.com/massalabs/wasm-simulation/tree/wasi-env I demonstrate how to pass values to https://bellard.org/quickjs/ interpreter on top of Wasmer runtime!

**Comment by adrien-zinger** [comment]
@gterzian @yvan-sraka @AureliaDolo
I worked on the crate [wasmer-as](https://github.com/onsails/wasmer-as) if we finally want to use assemblyscript: [look at this](https://github.com/adrien-zinger/wasmer-as/blob/master/tests/strings.rs)

I also wrote to the creator of this crate in order to know what he want and if it's what I've done. [link to the issue](https://github.com/onsails/wasmer-as/issues/4). What I want to do is to help the owner of wasmer-as to implement the rust version of some function from this [helper](https://github.com/AssemblyScript/assemblyscript/blob/main/lib/loader/index.js) provided by AssemblyScript. 

An other way is, re implement the _new, _deallocate that is dumped by AssemblyScript and set a data space in memory (with an constant?) and read write only in this memory space that will never be rewrote if the WA developer use a high level language.

But [wasi-data-rust](https://github.com/singlestore-labs/wasi-data-rust) can also be the solution! I haven't got the time today :sob: but I absolutely want to take a look at this repository!!

**Comment by adrien-zinger** [comment]
Finally in this repository we're using the project wasmer-as to communicate between rust and webassembly. That mean that for the moment we'll use only .wasm/.wat generated from the [AssemblyScript](https://github.com/AssemblyScript) project!

@AureliaDolo @gterzian @yvan-sraka I'll give you the access to the fork of [wasmer-as](https://github.com/adrien-zinger/wasmer-as) and open some issues.

**Comment by adrien-zinger** [comment]
@gterzian I let you close this issue if we answered you :smile:

**Comment by gterzian** [comment]
Ok, thanks for the info.
